### ISSUE TITLE
Bug posting encoded text?

### ISSUE THREAD

**Issue by jeffisfast** [jparise/vesta#13]
Hi,

Thanks for this library. I've got it working fine for text messages, but it seems to fail when posting any encoded text - my board just goes blank.  I did some experimenting and I think the bug is that it is improperly flagging a passed in list of encoded characters as text.  Observe the following output noting that it thinks it is a text message in both scenarios:

```
>>> result = vclient.post_message(config.VESTA_SUBSCRIPTION_ID, "foo")
>>> print(result)
{'message': {'id': 'ce7915b1-20fb-4cf9-bfca-0ac6c911b20f', 'text': 'foo', 'created': '1639946986010'}}

>>> result = vclient.post_message(config.VESTA_SUBSCRIPTION_ID, [[0, 0, 0, 0, 0, 0, 0, 13, 21, 12, 20, 9, 16, 12, 5, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 12, 9, 14, 5, 19, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 5, 24, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
>>> print(result)
{'message': {'id': '8ebe9257-6827-4d8e-8d11-b65b2a81cfec', 'text': None, 'created': '1639947016428'}}

```
Am I doing something wrong?  Many thanks!

**Comment by jparise** [comment]
I see the issue. When you pass a list of encoded characters, the Vestaboard API expects the list to contain six full rows of 22 characters. In your example above, the list only contains four rows.

Did you construct that list yourself, or are you using `encode_text()`? I debated whether `encode_text()` should always pad its result to all six rows, or if I should add an option for that behavior. Any opinion on that?

I'll also add some additional error checking to `Client.post_message()` so that it raises an exception if the encoded character list doesn't have the expected dimensions.

**Comment by natekspencer** [comment]
Came here to say I'm having the same issue. Based on the description of encode_text: `Encodes a string of text into rows of character codes.`, I would expect it to produce the full set of rows.

**Comment by jeffisfast** [comment]
Thanks @jparise .  I used encode_text() to construct the array.  I suggest it always pad with the logic that using pprint will help others figure out where to customize their output.

**Comment by natekspencer** [comment]
Yeah, it seems that all of the `encode` functions don't do any good at the moment unless the user knows how to convert them all back to text to post to the board or to construct their own full array. Neither of which seem very intuitive.

**Comment by jparise** [comment]
> Yeah, it seems that all of the `encode` functions don't do any good at the moment unless the user knows how to convert them all back to text to post to the board or to construct their own full array. Neither of which seem very intuitive.

That sounds a bit harsh. For my own projects, I only use the encoding functions when I'm manually building up my own full array. (Otherwise, I just pass a string to `Client.post_message()`.) I have found `encode()` and `encode_row()` to be very useful for producing layouts like this:

![sign](https://user-images.githubusercontent.com/10311/146694420-62aa462b-1322-463d-8733-665b1c66fa5b.jpeg)

I agree it would be friendlier for `encode_text()` to do the remaining bit of work, especially because it produces a variable number of rows, so I'll add that as the default behavior shortly.

I've been toying with the idea of introducing a `Board` class that would accept "fragments" of encoded characters and lay them out onto a full "board", producing the full two-dimensional array of posting, but I haven't needed something that complex yet.

**Comment by natekspencer** [comment]
Sorry, I didn't mean it to be harsh. And I truly appreciate this library already. It probably just needs to be a little more clear on how they are utilized.

**Comment by jeffisfast** [comment]
@jparise Love your weather display.  My Vestaboard has finally shipped, don't have yet, but I've written some fun modules to: show weather, show jokes, show the current time, and show the word of the day.  I have a few more that I want to make too.  Would you be willing to share the code for your weather and any other modules?  Public or private is fine - perhaps we can create a package of cool screens for all to enjoy?

**Comment by jparise** [comment]
Version 0.7.0 has just been released (and published to PyPI). It should address all of the above. Thanks for providing the feedback!

**Comment by jparise** [comment]
@jeffisfast I've gotten close to packaging up that code a few times, but it's a bit of a mess (in terms of hardcoded URLs and things). I'll try to find the time soon!
